(function(a){const{esc:p,icon:i}=a,l=window.SB;if(!l)return;let n=null,c=!1;const r=async(t,s={})=>{const{data:e,error:o}=await l.functions.invoke("setup",{body:Object.assign({action:t},s)});if(o){let u="";try{u=(await o.context.json()).error}catch{}throw new Error(u||"הפעולה נכשלה")}return e},d=async()=>{if(!c){c=!0;try{n=await r("status")}catch(t){n={error:t.message}}c=!1,a.R.view==="settings"&&a.render()}},b=async(t,s)=>{const{error:e}=await l.rpc("set_secret",{p_key:t,p_value:s});if(e)throw e},m=t=>`<span class="pill ${t?"p-ok":"p-warn"}">${t?"מחובר":"לא מחובר"}</span>`;a.act("cx-ai",async t=>{const s=document.getElementById("cx_ai").value.trim();if(!/^sk-ant-/.test(s)){a.toast("המפתח מתחיל ב-sk-ant-","bad");return}t.disabled=!0;try{await b("ANTHROPIC_API_KEY",s),a.toast("המפתח נשמר"),await new Promise(e=>setTimeout(e,1500)),n=null,d()}catch{a.toast("השמירה נכשלה","bad")}t.disabled=!1}),a.act("cx-tg",async t=>{const s=document.getElementById("cx_tg").value.trim();if(!/^\d+:[\w-]{20,}$/.test(s)){a.toast("הקוד נראה כך: 123456789:ABC...","bad");return}t.disabled=!0,t.innerHTML='<span class="spin"></span> מחבר...';try{await b("TELEGRAM_BOT_TOKEN",s),await new Promise(o=>setTimeout(o,1200));const e=await r("telegram");if(!e.ok)throw new Error(e.error);a.modal({title:"שלב אחרון: לחיצה אחת בטלגרם",body:`<p style="margin-top:0">הבוט <b dir="ltr">@${p(e.bot)}</b> מוכן. לחץ על הכפתור, טלגרם ייפתח, ולחץ שם על <b>Start</b> (או "התחל").</p><a class="btn pri" href="${p(e.link)}" target="_blank" rel="noopener">${i("send",15)} פתיחה בטלגרם</a><p class="small muted" style="margin-bottom:0">אחרי הלחיצה תקבל בטלגרם הודעה "מחובר!". מאותו רגע רק הצ׳אט שלך מקבל הודעות מהמערכת.</p>`,foot:'<button class="btn" data-close>סגירה</button>'}),setTimeout(()=>{n=null,d()},15e3)}catch(e){a.toast(e.message||"החיבור נכשל","bad")}t.disabled=!1,t.textContent="חיבור"}),a.act("cx-tgtest",async()=>{try{const t=await r("test-telegram");a.toast(t.ok?"נשלחה הודעת בדיקה לטלגרם":"ההודעה לא נשלחה. חבר שוב את הבוט.",t.ok?void 0:"bad")}catch(t){a.toast(t.message,"bad")}}),a.act("cx-tpl",async t=>{t.disabled=!0,t.innerHTML='<span class="spin"></span> מייבא...';try{const s=await r("import-templates");a.toast(s.done&&s.done.length?`יובאו ${s.done.length} תבניות: ${s.done.join(", ")}`:"הייבוא נכשל",s.done&&s.done.length?void 0:"bad")}catch(s){a.toast(s.message,"bad")}t.disabled=!1,t.textContent="ייבוא התבניות"}),a.connectionsCard=()=>{const t=n&&n.set||{},s=Object.keys((a.get("settings","wordTemplates")||{}).items||{}).length;return n||d(),`<div class="card" id="cx"><div class="card-h"><h2>${i("link",17)} חיבורים</h2>${n?"":'<span class="spin"></span>'}</div><div class="card-b" style="display:grid;gap:18px">
  <div><div class="kv-row"><b>${i("send",15)} בוט טלגרם (סיכום בוקר, לידים, שליחה בלחיצה)</b>${m(t.TELEGRAM_CHAT_ID)}</div>
    ${t.TELEGRAM_CHAT_ID?'<div class="btn-row" style="margin-top:8px"><button class="btn sm" data-a="cx-tgtest">שליחת הודעת בדיקה</button></div>':`<ol class="small" style="margin:8px 0;padding-inline-start:20px;line-height:1.8">
      <li>בטלגרם, חפש <b dir="ltr">@BotFather</b> ופתח אותו.</li><li>שלח לו <b dir="ltr">/newbot</b>, ואז שם לבוט (למשל: משרד דבול), ואז שם משתמש באנגלית שמסתיים ב-bot (למשל: <span dir="ltr">dabul_office_bot</span>).</li><li>הוא ישלח לך קוד ארוך. העתק אותו לכאן ולחץ "חיבור".</li></ol>`}
    <div class="btn-row"><input class="in" id="cx_tg" dir="ltr" data-nokeep="1" placeholder="${t.TELEGRAM_BOT_TOKEN?"קוד הבוט שמור. להחלפה הדבק קוד חדש":"123456789:ABC..."}" style="flex:1;min-width:200px"><button class="btn sm pri" data-a="cx-tg">חיבור</button></div></div>
  <div><div class="kv-row"><b>${i("ai",15)} העוזר החכם (קריאת חוזים ומסמכים)</b>${m(t.ANTHROPIC_API_KEY)}</div>
    ${t.ANTHROPIC_API_KEY?"":'<p class="small muted" style="margin:6px 0">נכנסים ל-<a href="https://console.anthropic.com/settings/keys" target="_blank" rel="noopener" dir="ltr">console.anthropic.com</a>, יוצרים מפתח (Create Key), טוענים קרדיט קטן בחיוב לפי שימוש, ומדביקים כאן.</p>'}
    <div class="btn-row"><input class="in" id="cx_ai" dir="ltr" type="password" data-nokeep="1" placeholder="${t.ANTHROPIC_API_KEY?"המפתח שמור. להחלפה הדבק מפתח חדש":"sk-ant-..."}" style="flex:1;min-width:200px"><button class="btn sm pri" data-a="cx-ai">שמירה</button></div></div>
  <div><div class="kv-row"><b>${i("doc",15)} תבניות Word של המשרד</b><span class="pill ${s?"p-ok":"p-warn"}">${s?`${s} תבניות`:"לא יובאו"}</span></div>
    <p class="small muted" style="margin:6px 0">שטר מכר, ייפויי כוח, בקשה לרישום הערת אזהרה וביטול הערה, מהמערכת הקודמת. המערכת הקודמת לא משתנה.</p><button class="btn sm" data-a="cx-tpl">ייבוא התבניות</button></div>
  ${a.leadsConnectHtml?a.leadsConnectHtml(n):""}
  </div></div>`};const g=a.V.settings.render;a.V.settings.render=function(t){g.call(this,t);const s=t.querySelector(".page-head");if(!s)return;const e=document.createElement("div");e.style.marginBottom="16px",e.innerHTML=a.connectionsCard(),s.after(e)}})(window.O);
