(function(t){const{esc:o,icon:p,fmtDate:x,rel:M,today:v,addDays:h,waLink:T,fmtPhone:F}=t,k=((window.OFFICE_CONFIG||{}).appUrl||location.href.split("#")[0].replace(/[^/]*$/,""))+"sign.html";t.signBase=k;const S=e=>`${k}#${e.id}`,j=()=>{const e=new Uint8Array(24);return crypto.getRandomValues(e),Array.from(e,n=>"ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789"[n%56]).join("")},H=async e=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(e))),n=>n.toString(16).padStart(2,"0")).join(""),q=e=>String(e||"").split(/[ ,(]/)[0],I={pending:["ממתין לחתימה","p-warn"],signed:["נחתם","p-ok"],cancelled:["בוטל",""],expired:["פג תוקף","p-bad"],locked:["ננעל","p-bad"]},R=e=>e.status==="pending"&&(e.fails||0)>=5?"locked":e.status==="pending"&&e.expires&&e.expires<v()?"expired":e.status,C=e=>`שלום ${q(e.signerName)},
מצורף קישור לחתימה מרחוק על "${e.title}".
פותחים את הקישור בטלפון, ${e.verifyHash?"מקלידים את 4 הספרות האחרונות של תעודת הזהות, ":""}עוברים על המסמך וחותמים במקומות המסומנים. זה לוקח דקה.
${S(e)}${e.expires?`
הקישור בתוקף עד ${x(e.expires)}.`:""}

${t.settings().signature}`;t.act("sig-remote",async()=>{const e=t._sig;if(!e||!e.file)return;if(!(e.marks||[]).some(a=>(a.type||"sig")==="sig"||a.type==="init")){t.toast("סמן לפחות מקום אחד לחתימה על המסמך","bad");return}const n=t.all("clients").sort((a,d)=>String(a.name).localeCompare(String(d.name),"he")),s=a=>t.all("deals").filter(d=>!a||(d.clientIds||[]).includes(a)),l=t.get("clients",e.clientId),c=a=>String(a&&a.idNo||"").replace(/\D/g,"").slice(-4);t.modal({title:"שליחה לחתימה מרחוק",wide:!0,body:`<div class="fg">
    <div class="f"><label for="rc">לקוח</label><select id="rc" class="in"><option value="">בחר לקוח</option>${n.map(a=>`<option value="${a.id}"${l&&a.id===l.id?" selected":""}>${o(a.name)}</option>`).join("")}</select></div>
    <div class="f"><label for="rd">עסקה (לתיוק)</label><select id="rd" class="in"></select></div>
    <div class="f"><label for="rn">שם החותם</label><input id="rn" class="in" value="${o(e.signer||l&&l.name||"")}"></div>
    <div class="f"><label for="rp">טלפון</label><input id="rp" class="in num" dir="ltr" value="${o(l&&l.phone||"")}"></div>
    <div class="f"><label for="rt">שם המסמך</label><input id="rt" class="in" value="${o(e.name.replace(/\.pdf$/i,""))}"></div>
    <div class="f"><label for="rx">הקישור בתוקף</label><select id="rx" class="in"><option value="3">3 ימים</option><option value="7">שבוע</option><option value="14" selected>שבועיים</option><option value="30">חודש</option></select></div>
    <div class="f full"><label for="rv">אימות זהות: 4 הספרות האחרונות של תעודת הזהות</label><input id="rv" class="in num" dir="ltr" inputmode="numeric" maxlength="4" style="max-width:140px" value="${o(c(l))}"><small class="muted">הלקוח יקליד אותן לפני שיראה את המסמך. אחרי 5 טעויות הקישור ננעל. אפשר להשאיר ריק כדי לוותר על האימות.</small></div>
    <div class="f full"><label for="rm">הערה ללקוח (לא חובה)</label><textarea id="rm" class="in" rows="2" placeholder="למשל: נא לחתום בכל העמודים המסומנים"></textarea></div></div>
    <p class="small muted" style="margin-bottom:0">${e.marks.length} מקומות מסומנים ב-${new Set(e.marks.map(a=>a.page)).size} עמודים. הלקוח יחתום פעם אחת והחתימה תיכנס לכל המקומות.</p>`,foot:`<button class="btn pri" id="rgo">${p("send",15)} יצירת קישור</button><button class="btn" data-close>ביטול</button>`,onMount:(a,d)=>{const i=r=>a.querySelector(r),N=()=>{const r=i("#rc").value,b=s(r);i("#rd").innerHTML='<option value="">ללא עסקה</option>'+b.map(g=>`<option value="${g.id}">${o(g.address||g.title||g.id)}</option>`).join(""),b.length===1&&r&&(i("#rd").value=b[0].id)};N(),i("#rc").onchange=()=>{const r=t.get("clients",i("#rc").value);r&&(i("#rn").value=r.name||"",i("#rp").value=r.phone||"",i("#rv").value=c(r)),N()},i("#rgo").onclick=async()=>{const r=i("#rn").value.trim(),b=i("#rp").value.trim(),g=i("#rv").value.trim();if(!r){t.toast("חסר שם החותם","bad");return}if(g&&!/^\d{4}$/.test(g)){t.toast("אימות זהות: בדיוק 4 ספרות, או להשאיר ריק","bad");return}const $=i("#rgo");$.disabled=!0,$.innerHTML='<span class="spin"></span> מעלה...';try{const m=j(),A=`sign/${v()}/${m}.pdf`,{error:D}=await window.SB.storage.from("files").upload(A,e.file,{contentType:"application/pdf"});if(D)throw D;const f={title:i("#rt").value.trim()||e.name,signerName:r,phone:b,clientId:i("#rc").value,dealId:i("#rd").value,path:A,pages:e.pages,marks:e.marks.map(u=>({type:u.type||"sig",page:u.page,x:Math.round(u.x),y:Math.round(u.y),w:u.w||180,h:u.h||70,pw:u.pw,ph:u.ph})),status:"pending",expires:h(v(),+i("#rx").value),created:new Date().toISOString(),officeName:t.settings().office||"",note:i("#rm").value.trim(),verifyHash:g?await H(m+":"+g):""};await t.save("signreqs",m,f);const y=f.dealId?["deal",f.dealId]:f.clientId?["client",f.clientId]:null;y&&await t.log(y[0],y[1],`נשלח לחתימה מרחוק: ${f.title}`,"system"),d(),t._sig=null,t.render(),w(Object.assign({id:m},f))}catch(m){console.error(m),t.toast("יצירת הקישור נכשלה: "+(m.message||""),"bad"),$.disabled=!1,$.textContent="נסה שוב"}}}})});const w=e=>{const n=S(e);t.modal({title:"הקישור לחתימה מוכן",body:`<p class="muted" style="margin-top:0">${o(e.signerName)} יחתום על "${o(e.title)}" ישירות מהטלפון. כשיחתום תקבל הודעה בטלגרם, והמסמך החתום יישמר לבד ${e.dealId?"בתיק העסקה":e.clientId?"בתיק הלקוח":"ברשימת המסמכים"}.</p>
    <div class="btn-row" style="margin-bottom:12px"><input class="in" readonly dir="ltr" value="${o(n)}" style="flex:1;min-width:200px" data-nokeep="1"><button class="btn" id="lcp">${p("copy",14)} העתקה</button></div>
    ${t.normPhone(e.phone)?`<a class="btn pri wa" target="_blank" rel="noopener" href="${o(T(e.phone,C(e)))}">${p("wa",15)} שליחה בוואטסאפ ל${o(q(e.signerName))}</a>`:'<p class="small muted">אין מספר טלפון. העתק את הקישור ושלח אותו ללקוח.</p>'}
    <p class="small muted" style="margin-bottom:0">אם הלקוח לא יחתום תוך ${+t.settings().signNudgeDays||2} ימים, המערכת תכין לו תזכורת עם הקישור.</p>`,foot:'<button class="btn" data-close>סגירה</button>',onMount:s=>{s.querySelector("#lcp").onclick=()=>t.copy(C(e))}})};t.act("sr-link",(e,n)=>{const s=t.get("signreqs",n.id);s&&w(s)}),t.act("sr-cancel",async(e,n)=>{const s=t.get("signreqs",n.id);s&&await t.confirm(`לבטל את הקישור לחתימה על "${s.title}"? הלקוח לא יוכל לחתום בו יותר.`,"ביטול הקישור",!0)&&(await t.patch("signreqs",s.id,{status:"cancelled",cancelledAt:new Date().toISOString()}),t.toast("הקישור בוטל"))}),t.act("sr-renew",async(e,n)=>{const s=t.get("signreqs",n.id);s&&(await t.patch("signreqs",s.id,{status:"pending",fails:0,expires:h(v(),14)}),t.toast("הקישור חודש לשבועיים"),w(Object.assign({},s,{status:"pending",expires:h(v(),14)})))}),t.signReqRow=e=>{const n=R(e),[s,l]=I[n]||I.pending,c=n==="signed"?`נחתם ${x(String(e.signedAt).slice(0,10))}`:`נשלח ${M(String(e.created).slice(0,10))}${e.openedAt?" · נפתח":" · עוד לא נפתח"}`;return`<div class="li"><span class="ic ${n==="signed"?"i-ok":n==="pending"?"i-warn":"i-bad"}">${p("sign",15)}</span><div class="grow"><b>${o(e.title)}</b><small>${o(e.signerName||"")} · ${c} · ${(e.marks||[]).length} מקומות</small></div>
    <span class="pill ${l}">${s}</span>
    ${n==="signed"&&e.signedPath?`<a class="btn xs" href="sbfile:${o(e.signedPath)}" target="_blank" rel="noopener">${p("eye",13)} חתום</a>`:""}
    ${n==="pending"?`<button class="btn xs" data-a="sr-link" data-id="${e.id}">${p("link",13)} קישור</button><button class="btn xs ghost" data-a="sr-cancel" data-id="${e.id}" aria-label="ביטול">${p("x",13)}</button>`:""}
    ${n==="expired"||n==="locked"?`<button class="btn xs" data-a="sr-renew" data-id="${e.id}">חידוש</button>`:""}</div>`},t.signReqs=e=>t.all("signreqs").filter(n=>!e||e(n)).sort((n,s)=>String(s.created).localeCompare(String(n.created)));const P=t.V.signatures.render;t.V.signatures.render=function(e){P.call(this,e);const n=e.querySelector(".page-head p");n&&(n.textContent="חתימה במשרד על טאבלט, או שליחת קישור ללקוח לחתימה מרחוק: מעלים PDF, מסמנים איפה חותמים (בכל עמוד שצריך), והמסמך החתום נשמר לבד בתיק.");const s=t.signReqs(),l=e.querySelector(".g-main > .card:last-child");if(!l)return;const c=document.createElement("div");c.className="card";const a=s.filter(i=>R(i)==="pending").length;c.innerHTML=`<div class="card-h"><h2>${p("send",16)} חתימות מרחוק</h2><span class="sub">${a?`${a} ממתינים`:s.length}</span></div><div class="list">${s.slice(0,30).map(t.signReqRow).join("")||t.empty("עדיין לא נשלחו",'מעלים PDF, מסמנים מקומות ולוחצים "שליחה לחתימה מרחוק"')}</div>`;const d=document.createElement("div");d.className="grid",d.style.alignContent="start",l.replaceWith(d),d.appendChild(c),d.appendChild(l)};const E=t.V.deal.render;t.V.deal.render=function(e){E.call(this,e);const n=t.get("deals",t.R.id);if(!n)return;const s=t.signReqs(c=>c.dealId===n.id);if(!s.length||!["flow","docs"].includes(t.ui("deal","tab","flow")))return;const l=document.createElement("div");l.className="card",l.style.marginTop="16px",l.innerHTML=`<div class="card-h"><h2>${p("sign",16)} חתימות מרחוק</h2></div><div class="list">${s.map(t.signReqRow).join("")}</div>`,e.appendChild(l)}})(window.O);
