(function(t){const{esc:r,icon:s,waLink:f,fmtPhone:b}=t,c=window.OFFICE_CONFIG||{},p=c.portalUrl||location.href.split("#")[0].replace(/[^/]*$/,"")+"portal.html",h=()=>{const e=new Uint8Array(24);return crypto.getRandomValues(e),Array.from(e,a=>"ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789"[a%56]).join("")};t.portalUrl=e=>e&&e.portalToken&&!e.portalOff?`${p}#${e.portalToken}`:"",t.ensurePortal=async e=>{if(e.portalToken&&!e.portalOff)return t.portalUrl(e);const a=e.portalToken||h();return await t.patch("deals",e.id,{portalToken:a,portalOff:!1}),await t.log("deal",e.id,"נוצר קישור אישי ללקוח","system"),`${p}#${a}`},t.act("portal-link",async(e,a)=>{const n=t.get("deals",a.id);if(!n)return;const l=await t.ensurePortal(n),d=t.dealClients(n),g=o=>`שלום ${String(o.name||"").split(/[ ,(]/)[0]},
זה הקישור האישי שלך למעקב אחרי העסקה (${n.address}). בקישור רואים את מועד החתימה, מועד המסירה, השלבים שכבר הושלמו ומה השלב הבא, ואפשר להוריד משם את החוזה. הדף מתעדכן לבד בכל פעם שאנחנו מתקדמים:
${l}

${t.settings().signature}`;t.modal({title:"קישור אישי ללקוח",wide:!0,body:`<p class="muted" style="margin-top:0">דף מעקב לעסקה ${r(n.address)}. הלקוח רואה רק את העסקה שלו: מועדים, שלבים, לוח התשלומים, ואת החוזה והמסמכים החתומים להורדה. בלי סיסמה, בלי מספרי זהות ובלי שכר טרחה.</p>
    <div class="linkbox"><input class="in" id="plink" readonly dir="ltr" value="${r(l)}" data-nokeep="1" aria-label="הקישור"></div>
    <div class="btn-grid" style="margin-bottom:14px"><button class="btn" id="pcopy">${s("copy",16)} העתקת הקישור</button>${navigator.share?`<button class="btn" id="pshare">${s("send",16)} שיתוף</button>`:""}<a class="btn ghost" href="${r(l)}" target="_blank" rel="noopener">${s("eye",16)} תצוגה</a></div>
    <div class="list card" style="box-shadow:none">${d.map(o=>`<div class="li">${t.avatar(o.name)}<div class="grow"><b>${r(o.name)}</b><small class="num">${r(b(o.phone)||"אין טלפון")}</small></div>${t.normPhone(o.phone)?`<a class="btn sm wa" target="_blank" rel="noopener" href="${r(f(o.phone,g(o)))}">${s("wa",14)} שליחה בוואטסאפ</a>`:""}</div>`).join("")||'<p class="muted">אין לקוחות בעסקה.</p>'}</div>
    <p class="small muted" style="margin-bottom:0">הקישור נוסף אוטומטית גם לכל הודעת עדכון שהמערכת מכינה ללקוח בעסקה הזו.</p>`,foot:`<button class="btn danger" id="poff">${s("x",14)} ביטול הקישור</button><button class="btn" data-close>סגירה</button>`,onMount:(o,v)=>{const u=o.querySelector("#pcopy");u.onclick=()=>t.copy(l,u);const m=o.querySelector("#pshare");m&&(m.onclick=()=>navigator.share({title:"מעקב אחרי העסקה",url:l}).catch(()=>{})),o.querySelector("#poff").onclick=async()=>{await t.confirm("לבטל את הקישור? הלקוח לא יוכל להיכנס אליו יותר. אפשר ליצור קישור חדש בכל זמן.","ביטול הקישור",!0)&&(await t.patch("deals",n.id,{portalOff:!0,portalToken:null}),v(),t.toast("הקישור בוטל"))}}})});const y=t.V.deal.render;t.V.deal.render=function(e){y.call(this,e);const a=t.get("deals",t.R.id),n=e.querySelector('[data-a="edit-deal"]');if(!a||!n)return;const l=document.createElement("button");l.className="btn",l.dataset.a="portal-link",l.dataset.id=a.id,l.innerHTML=`${s("link",16)} קישור ללקוח`,n.parentElement.insertBefore(l,n)};const i=location.hash.match(/^#(leads|deal|client)\/([\w-]+)$/);if(i){const e=Date.now(),a=setInterval(()=>{(t.S.loaded&&t.S.loaded.leads&&t.get(i[1]==="leads"?"leads":i[1]+"s",i[2])||Date.now()-e>1e4)&&(clearInterval(a),history.replaceState(null,"",location.pathname),t.go(i[1],i[2]))},300)}t.portalBase=p;const $=t.V.auto.render;t.V.auto.render=function(e){$.call(this,e);const a=e.querySelectorAll(".g-main > .grid")[1];if(!a)return;const n=(c.functions||"")+"/lead",l=document.createElement("div");l.className="card",l.innerHTML=`<div class="card-h"><h2>${s("lead",17)} לידים מהאתר</h2><span class="pill ${c.functions?"p-ok":"p-warn"}">${c.functions?"פעיל":"לא מחובר"}</span></div><div class="card-b small"><p class="muted" style="margin:0 0 8px">כתובת לקליטת לידים. מדביקים אותה בהגדרות הטופס באתר (Webhook). כל פנייה נכנסת לכאן ומגיעה אליך לטלגרם.</p><div class="btn-row"><input class="in" readonly dir="ltr" value="${r(n)}" style="flex:1;min-width:180px" data-nokeep="1"><button class="btn sm" id="lcopy">${s("copy",13)} העתקה</button></div></div>`,a.insertBefore(l,a.firstChild);const d=l.querySelector("#lcopy");d.onclick=()=>t.copy(n,d)};const w=t.V.settings.render;t.V.settings.render=function(e){w.call(this,e);const a=e.querySelector(".page-head .btn-row");if(a&&window.OFFICE_SIGNOUT){const n=document.createElement("button");n.className="btn",n.innerHTML=`${s("arrow",15)} יציאה מהמערכת`,n.onclick=()=>window.OFFICE_SIGNOUT(),a.appendChild(n)}}})(window.O);
