(function(t){const{esc:o,icon:d,fmtDate:S,rel:M,today:b,addDays:h,waLink:T,fmtPhone:F}=t,x=((window.OFFICE_CONFIG||{}).appUrl||location.href.split("#")[0].replace(/[^/]*$/,""))+"sign.html";t.signBase=x;const q=e=>`${x}#${e.id}`,j=()=>{const e=new Uint8Array(24);return crypto.getRandomValues(e),Array.from(e,n=>"ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789"[n%56]).join("")},H=async e=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(e))),n=>n.toString(16).padStart(2,"0")).join(""),I=e=>String(e||"").split(/[ ,(]/)[0],R={pending:["ממתין לחתימה","p-warn"],signed:["נחתם","p-ok"],cancelled:["בוטל",""],expired:["פג תוקף","p-bad"],locked:["ננעל","p-bad"]},C=e=>e.status==="pending"&&(e.fails||0)>=5?"locked":e.status==="pending"&&e.expires&&e.expires<b()?"expired":e.status,y=e=>`שלום ${I(e.signerName)},
מצורף קישור לחתימה מרחוק על "${e.title}".
פותחים את הקישור בטלפון, ${e.verifyHash?"מקלידים את 4 הספרות האחרונות של תעודת הזהות, ":""}עוברים על המסמך וחותמים במקומות המסומנים. זה לוקח דקה.
${q(e)}${e.expires?`
הקישור בתוקף עד ${S(e.expires)}.`:""}

${t.settings().signature}`;t.act("sig-remote",async()=>{const e=t._sig;if(!e||!e.file)return;if(!(e.marks||[]).some(a=>(a.type||"sig")==="sig"||a.type==="init")){t.toast("סמן לפחות מקום אחד לחתימה על המסמך","bad");return}const n=t.all("clients").sort((a,p)=>String(a.name).localeCompare(String(p.name),"he")),s=a=>t.all("deals").filter(p=>!a||(p.clientIds||[]).includes(a)),i=t.get("clients",e.clientId),c=a=>String(a&&a.idNo||"").replace(/\D/g,"").slice(-4);t.modal({title:"שליחה לחתימה מרחוק",wide:!0,body:`<div class="fg">
    <div class="f"><label for="rc">לקוח</label><select id="rc" class="in"><option value="">בחר לקוח</option>${n.map(a=>`<option value="${a.id}"${i&&a.id===i.id?" selected":""}>${o(a.name)}</option>`).join("")}</select></div>
    <div class="f"><label for="rd">עסקה (לתיוק)</label><select id="rd" class="in"></select></div>
    <div class="f"><label for="rn">שם החותם</label><input id="rn" class="in" value="${o(e.signer||i&&i.name||"")}"></div>
    <div class="f"><label for="rp">טלפון</label><input id="rp" class="in num" dir="ltr" value="${o(i&&i.phone||"")}"></div>
    <div class="f"><label for="rt">שם המסמך</label><input id="rt" class="in" value="${o(e.name.replace(/\.pdf$/i,""))}"></div>
    <div class="f"><label for="rx">הקישור בתוקף</label><select id="rx" class="in"><option value="3">3 ימים</option><option value="7">שבוע</option><option value="14" selected>שבועיים</option><option value="30">חודש</option></select></div>
    <div class="f full"><label for="rv">אימות זהות: 4 הספרות האחרונות של תעודת הזהות</label><input id="rv" class="in num" dir="ltr" inputmode="numeric" maxlength="4" style="max-width:140px" value="${o(c(i))}"><small class="muted">הלקוח יקליד אותן לפני שיראה את המסמך. אחרי 5 טעויות הקישור ננעל. אפשר להשאיר ריק כדי לוותר על האימות.</small></div>
    <div class="f full"><label for="rm">הערה ללקוח (לא חובה)</label><textarea id="rm" class="in" rows="2" placeholder="למשל: נא לחתום בכל העמודים המסומנים"></textarea></div></div>
    <p class="small muted" style="margin-bottom:0">${e.marks.length} מקומות מסומנים ב-${new Set(e.marks.map(a=>a.page)).size} עמודים. הלקוח יחתום פעם אחת והחתימה תיכנס לכל המקומות.</p>`,foot:`<button class="btn pri" id="rgo">${d("send",15)} יצירת קישור</button><button class="btn" data-close>ביטול</button>`,onMount:(a,p)=>{const l=r=>a.querySelector(r),N=()=>{const r=l("#rc").value,v=s(r);l("#rd").innerHTML='<option value="">ללא עסקה</option>'+v.map(u=>`<option value="${u.id}">${o(u.address||u.title||u.id)}</option>`).join(""),v.length===1&&r&&(l("#rd").value=v[0].id)};N(),l("#rc").onchange=()=>{const r=t.get("clients",l("#rc").value);r&&(l("#rn").value=r.name||"",l("#rp").value=r.phone||"",l("#rv").value=c(r)),N()},l("#rgo").onclick=async()=>{const r=l("#rn").value.trim(),v=l("#rp").value.trim(),u=l("#rv").value.trim();if(!r){t.toast("חסר שם החותם","bad");return}if(u&&!/^\d{4}$/.test(u)){t.toast("אימות זהות: בדיוק 4 ספרות, או להשאיר ריק","bad");return}const $=l("#rgo");$.disabled=!0,$.innerHTML='<span class="spin"></span> מעלה...';try{const m=j(),A=`sign/${b()}/${m}.pdf`,{error:D}=await window.SB.storage.from("files").upload(A,e.file,{contentType:"application/pdf"});if(D)throw D;const f={title:l("#rt").value.trim()||e.name,signerName:r,phone:v,clientId:l("#rc").value,dealId:l("#rd").value,path:A,pages:e.pages,marks:e.marks.map(g=>({type:g.type||"sig",page:g.page,x:Math.round(g.x),y:Math.round(g.y),w:g.w||180,h:g.h||70,pw:g.pw,ph:g.ph})),status:"pending",expires:h(b(),+l("#rx").value),created:new Date().toISOString(),officeName:t.settings().office||"",note:l("#rm").value.trim(),verifyHash:u?await H(m+":"+u):""};await t.save("signreqs",m,f);const k=f.dealId?["deal",f.dealId]:f.clientId?["client",f.clientId]:null;k&&await t.log(k[0],k[1],`נשלח לחתימה מרחוק: ${f.title}`,"system"),p(),t._sig=null,t.render(),w(Object.assign({id:m},f))}catch(m){console.error(m),t.toast("יצירת הקישור נכשלה: "+(m.message||""),"bad"),$.disabled=!1,$.textContent="נסה שוב"}}}})});const w=e=>{const n=q(e);t.modal({title:"הקישור לחתימה מוכן",body:`<p class="muted" style="margin-top:0">${o(e.signerName)} יחתום על "${o(e.title)}" ישירות מהטלפון. כשיחתום תקבל הודעה בטלגרם, והמסמך החתום יישמר לבד ${e.dealId?"בתיק העסקה":e.clientId?"בתיק הלקוח":"ברשימת המסמכים"}.</p>
    <div class="linkbox"><input class="in" readonly dir="ltr" value="${o(n)}" data-nokeep="1" aria-label="הקישור"></div>
    <div class="btn-grid">${t.normPhone(e.phone)?`<a class="btn wa" target="_blank" rel="noopener" href="${o(T(e.phone,y(e)))}">${d("wa",16)} וואטסאפ ל${o(I(e.signerName))}</a>`:""}<button class="btn" id="lcp">${d("copy",16)} העתקת ההודעה</button>${navigator.share?`<button class="btn" id="lsh">${d("send",16)} שיתוף</button>`:""}<button class="btn ghost" id="lcu">${d("link",16)} העתקת הקישור בלבד</button></div>
    ${t.normPhone(e.phone)?"":'<p class="small muted">אין מספר טלפון. מעתיקים את ההודעה ושולחים ללקוח.</p>'}
    <p class="small muted" style="margin-bottom:0">אם הלקוח לא יחתום תוך ${+t.settings().signNudgeDays||2} ימים, המערכת תכין לו תזכורת עם הקישור.</p>`,foot:'<button class="btn" data-close>סגירה</button>',onMount:s=>{const i=s.querySelector("#lcp");i.onclick=()=>t.copy(y(e),i);const c=s.querySelector("#lcu");c.onclick=()=>t.copy(n,c);const a=s.querySelector("#lsh");a&&(a.onclick=()=>navigator.share({title:e.title,text:y(e)}).catch(()=>{}))}})};t.act("sr-link",(e,n)=>{const s=t.get("signreqs",n.id);s&&w(s)}),t.act("sr-cancel",async(e,n)=>{const s=t.get("signreqs",n.id);s&&await t.confirm(`לבטל את הקישור לחתימה על "${s.title}"? הלקוח לא יוכל לחתום בו יותר.`,"ביטול הקישור",!0)&&(await t.patch("signreqs",s.id,{status:"cancelled",cancelledAt:new Date().toISOString()}),t.toast("הקישור בוטל"))}),t.act("sr-renew",async(e,n)=>{const s=t.get("signreqs",n.id);s&&(await t.patch("signreqs",s.id,{status:"pending",fails:0,expires:h(b(),14)}),t.toast("הקישור חודש לשבועיים"),w(Object.assign({},s,{status:"pending",expires:h(b(),14)})))}),t.signReqRow=e=>{const n=C(e),[s,i]=R[n]||R.pending,c=n==="signed"?`נחתם ${S(String(e.signedAt).slice(0,10))}`:`נשלח ${M(String(e.created).slice(0,10))}${e.openedAt?" · נפתח":" · עוד לא נפתח"}`;return`<div class="li"><span class="ic ${n==="signed"?"i-ok":n==="pending"?"i-warn":"i-bad"}">${d("sign",15)}</span><div class="grow"><b>${o(e.title)}</b><small>${o(e.signerName||"")} · ${c} · ${(e.marks||[]).length} מקומות</small></div>
    <span class="pill ${i}">${s}</span>
    ${n==="signed"&&e.signedPath?`<a class="btn xs" href="sbfile:${o(e.signedPath)}" target="_blank" rel="noopener">${d("eye",13)} חתום</a>`:""}
    ${n==="pending"?`<button class="btn xs" data-a="sr-link" data-id="${e.id}">${d("link",13)} קישור</button><button class="btn xs ghost" data-a="sr-cancel" data-id="${e.id}" aria-label="ביטול">${d("x",13)}</button>`:""}
    ${n==="expired"||n==="locked"?`<button class="btn xs" data-a="sr-renew" data-id="${e.id}">חידוש</button>`:""}</div>`},t.signReqs=e=>t.all("signreqs").filter(n=>!e||e(n)).sort((n,s)=>String(s.created).localeCompare(String(n.created)));const P=t.V.signatures.render;t.V.signatures.render=function(e){P.call(this,e);const n=e.querySelector(".page-head p");n&&(n.textContent="חתימה במשרד על טאבלט, או שליחת קישור ללקוח לחתימה מרחוק: מעלים PDF, מסמנים איפה חותמים (בכל עמוד שצריך), והמסמך החתום נשמר לבד בתיק.");const s=t.signReqs(),i=e.querySelector(".g-main > .card:last-child");if(!i)return;const c=document.createElement("div");c.className="card";const a=s.filter(l=>C(l)==="pending").length;c.innerHTML=`<div class="card-h"><h2>${d("send",16)} חתימות מרחוק</h2><span class="sub">${a?`${a} ממתינים`:s.length}</span></div><div class="list">${s.slice(0,30).map(t.signReqRow).join("")||t.empty("עדיין לא נשלחו",'מעלים PDF, מסמנים מקומות ולוחצים "שליחה לחתימה מרחוק"')}</div>`;const p=document.createElement("div");p.className="grid",p.style.alignContent="start",i.replaceWith(p),p.appendChild(c),p.appendChild(i)};const E=t.V.deal.render;t.V.deal.render=function(e){E.call(this,e);const n=t.get("deals",t.R.id);if(!n)return;const s=t.signReqs(c=>c.dealId===n.id);if(!s.length||!["flow","docs"].includes(t.ui("deal","tab","flow")))return;const i=document.createElement("div");i.className="card",i.style.marginTop="16px",i.innerHTML=`<div class="card-h"><h2>${d("sign",16)} חתימות מרחוק</h2></div><div class="list">${s.map(t.signReqRow).join("")}</div>`,e.appendChild(i)}})(window.O);
