(function(a){const{esc:d,icon:u,today:b,addDays:w,diffDays:S,rel:g,fmtDate:T,money:E,waLink:j}=a,k=()=>{const t=a.allTasks().filter(e=>["overdue","today"].includes(a.taskBucket(e))),i=new Map;t.forEach(e=>{const s=e.dealId&&a.get("deals",e.dealId),c=e.leadId&&a.get("leads",e.leadId),n=e.matterId&&a.get("matters",e.matterId),m=!s&&!c&&!n&&e.clientId&&a.get("clients",e.clientId),v=s?"d:"+s.id:c?"l:"+c.id:n?"m:"+n.id:m?"c:"+m.id:"t:"+e.id;i.has(v)||i.set(v,s?{key:v,icon:"deal",title:s.address||"עסקה",sub:a.dealClientsText(s),go:["deal",s.id],dealId:s.id,tasks:[]}:c?{key:v,icon:"lead",title:c.name||"ליד",sub:c.area||"ליד",go:["leads",c.id],tasks:[]}:n?{key:v,icon:a.isInsolv&&a.isInsolv(n)?"scale":"gavel",title:a.isInsolv&&a.isInsolv(n)?a.debtorName(n):n.title,sub:a.isInsolv&&a.isInsolv(n)?"חדלות פירעון":(a.MATTER_KINDS||{})[n.kind]||"תיק",go:[a.isInsolv&&a.isInsolv(n)?"insolv":"matters",n.id],tasks:[]}:m?{key:v,icon:"users",title:m.name,sub:"לקוח",go:["client",m.id],tasks:[]}:{key:v,icon:"task",title:"",sub:"",single:!0,tasks:[]}),i.get(v).tasks.push(e)});const o=e=>Math.min(...e.tasks.map(s=>a.prioRank(s.priority)*10+(a.taskBucket(s)==="overdue"?0:5))),r=[...i.values()];return r.forEach(e=>{e.tasks.sort((s,c)=>a.prioRank(s.priority)-a.prioRank(c.priority)||String(s.due).localeCompare(String(c.due))),e.late=e.tasks.filter(s=>a.taskBucket(s)==="overdue").length,e.oldest=e.tasks.map(s=>s.due||"").sort()[0]}),r.sort((e,s)=>o(e)-o(s)||String(e.oldest).localeCompare(String(s.oldest)))};a.todayGroups=k;const h=t=>{const i=a.taskBucket(t)==="overdue";return`<div class="tline"><button class="tick" data-a="task-done" data-id="${d(t.id)}" aria-label="סימון כבוצע: ${d(t.title)}"></button><div class="grow click" data-a="task-open" data-id="${d(t.id)}"><b>${d(t.title)}</b><small>${i?`<span class="t-bad">באיחור ${d(g(t.due))}</span>`:"היום"}${t.desc&&t.smart?" · "+d(t.desc):""}</small></div>${t.smart&&t.cta?`<button class="btn xs" data-a="task-done" data-id="${d(t.id)}">${d(t.cta)}</button>`:a.prioRank(t.priority)<=1?a.prioPill(t.priority):""}</div>`},D=t=>{if(t.single)return`<div class="tgroup single">${h(t.tasks[0])}</div>`;const i=a.ui("home","open:"+t.key,!1),o=i?t.tasks:t.tasks.slice(0,3),r=t.tasks.filter(e=>e.auto&&!e.smart&&String(e.id).startsWith("auto:")).length;return`<div class="tgroup"><div class="tg-h"><span class="ic i-acc">${u(t.icon,16)}</span><div class="grow click" data-a="go" data-v="${t.go[0]}" data-id="${d(t.go[1])}"><b>${d(t.title)}</b><small>${d(t.sub)}${t.late?` · <span class="t-bad">${t.late} באיחור</span>`:""}</small></div>${r>1&&t.dealId?`<button class="btn xs ghost" data-a="group-done" data-id="${d(t.dealId)}" title="סימון כל השלבים שבאיחור כבוצעו">${u("check",13)} הכל בוצע</button>`:""}</div>
    ${o.map(h).join("")}${t.tasks.length>3?`<button class="tg-more" data-a="group-more" data-k="${d(t.key)}">${i?"הצגת פחות":`ועוד ${t.tasks.length-3}`}</button>`:""}</div>`};a.act("group-more",(t,i)=>a.setUi("home","open:"+i.k,!a.ui("home","open:"+i.k,!1))),a.act("group-done",async(t,i)=>{const o=a.get("deals",i.id);if(!o)return;const r=a.allTasks().filter(s=>s.dealId===o.id&&String(s.id).startsWith("auto:")&&["overdue","today"].includes(a.taskBucket(s)));if(!r.length||!await a.confirm(`לסמן ${r.length} שלבים בעסקה ${o.address} כבוצעו?
${r.map(s=>"• "+s.title).join(`
`)}`,"כן, הכל בוצע"))return;const e=Object.assign({},o.milestones||{});r.forEach(s=>{e[s.milestone]=b()}),await a.patch("deals",o.id,{milestones:e}),await a.log("deal",o.id,`סומנו כבוצעו: ${r.map(s=>s.title).join(", ")}`,"system"),a.toast(`${r.length} שלבים סומנו כבוצעו`)});const R=t=>`<div class="li inbox-i"><details class="grow"><summary><b>${d(t.label)}: ${d(t.name)}</b><small>${d(t.why)}</small></summary><div class="msg" style="margin-top:8px">${d(t.text)}</div></details>
  <div class="btn-row nowrap">${t.phone?`<a class="btn sm wa" data-a="ob-send" data-key="${d(t.key)}" href="${d(j(t.phone,t.text))}" target="_blank" rel="noopener">${u("wa",14)} שליחה</a>`:'<span class="tag">אין טלפון</span>'}<button class="btn icon ghost" data-a="ob-dismiss" data-key="${d(t.key)}" aria-label="דחייה" title="לא לשלוח">${u("x",15)}</button></div></div>`;a.V.home={title:"לטיפול היום",render(t){const i=b(),o=new Date().getHours(),r=o<12?"בוקר טוב":o<17?"צהריים טובים":o<21?"ערב טוב":"לילה טוב",e=k(),s=a.outboxCandidates(),c=e.reduce((l,$)=>l+$.tasks.length,0),n=e.reduce((l,$)=>l+$.late,0),m=a.all("deals"),v=m.filter(l=>!a.isClosed(l)),y=a.feeStats(),L=a.events(i,w(i,7)).filter(l=>["sign","hand","court","pay","inst"].includes(l.type)),f=a.debtors?a.debtors().filter(l=>!l.closed).map(l=>({m:l,p:a.ieActive(l)})).filter(l=>l.p&&a.ieRep(l.m,l.p.key).status!=="submitted"&&S(l.p.due)<=20):[],p=a.ui("home","f","tasks"),C=c||s.length?`${e.length} נושאים לטיפול${n?`, ${n} משימות באיחור`:""}${s.length?` · ${s.length} הודעות מוכנות לשליחה`:""}`:"הכל מטופל להיום";t.innerHTML=`
  <div class="today-head"><div><h1>${r}, יקיר</h1><p>${d(a.fmtDateLong(i))} · ${C}</p></div>${c+s.length>2?`<button class="btn sm" data-a="morning-run">${u("zap",15)} מעבר מהיר אחד-אחד</button>`:""}</div>
  <div class="stat-row">
    <button class="stat${n?" bad":""}" data-seg="f" data-v="tasks"><b>${c}</b><small>משימות להיום${n?` (${n} באיחור)`:""}</small></button>
    <button class="stat" data-seg="f" data-v="msgs"><b>${s.length}</b><small>הודעות לאישור</small></button>
    <button class="stat" data-a="go" data-v="deals"><b>${v.length}</b><small>עסקאות פעילות</small></button>
    <button class="stat" data-a="go" data-v="payments"><b>${a.moneyK(y.expected+y.instOpen)}</b><small>שכ״ט פתוח</small></button>
  </div>
  <div class="grid g-main">
    <div class="grid" style="align-content:start">
      <div class="card"><div class="card-h"><h2>${p==="msgs"?"הודעות מוכנות לשליחה":"לטיפול היום"}</h2>${a.segs("f",[["tasks","משימות",c],["msgs","הודעות",s.length]],p)}</div>
        ${p==="msgs"?`<div class="list">${s.slice(0,30).map(R).join("")||a.empty("אין הודעות שמחכות","המערכת מכינה הודעות ללקוחות לבד, והן יופיעו כאן לאישור.")}</div>${s.length>30?`<div class="card-f"><button class="btn sm" data-a="go" data-v="outbox">כל ההודעות (${s.length})</button></div>`:""}`:`<div class="tgroups">${e.slice(0,40).map(D).join("")||a.empty("הכל מטופל 🎉","אין משימות להיום. המערכת תוסיף לבד את הבאות בזמן.")}</div>${e.length>40?'<div class="card-f"><button class="btn sm" data-a="go" data-v="tasks">כל המשימות</button></div>':""}`}
      </div>
    </div>
    <div class="grid" style="align-content:start">
      ${f.length?`<div class="card"><div class="card-h"><h2>${u("scale",16)} דוחות לממונה</h2><button class="btn xs ghost" data-a="go" data-v="insolv">הכל</button></div><div class="list">${f.map(({m:l,p:$})=>{const I=a.ieRep(l,$.key).status||"";return`<div class="li click" data-a="go" data-v="insolv" data-id="${l.id}"><div class="grow"><b>${d(a.debtorName(l))}</b><small>${d(a.ieLabel($))} · עד ${T($.due)}</small></div><span class="pill ${a.IE_STATUS[I][1]}">${a.IE_STATUS[I][0]}</span></div>`}).join("")}</div></div>`:""}
      <div class="card"><div class="card-h"><h2>השבוע ביומן</h2><button class="btn xs ghost" data-a="go" data-v="calendar">ליומן</button></div>
        <div class="list">${L.slice(0,8).map(l=>`<div class="li click" data-a="ev-open" data-type="${l.type}" data-deal="${d(l.dealId||"")}" data-plan="${d(l.planId||"")}" data-matter="${d(l.matterId||"")}"><div class="cal-d"><b>${a.parse(l.date).getDate()}</b><small>${a.parse(l.date).toLocaleDateString("he-IL",{weekday:"short"})}</small></div><div class="grow"><b>${d(l.title)}</b><small>${g(l.date)}</small></div></div>`).join("")||a.empty("שבוע פנוי","אין חתימות, מסירות או דיונים השבוע.")}</div></div>
      <div class="card autostrip-s click" data-a="go" data-v="auto">${u("zap",16)}<span>המערכת עובדת ברקע: מכינה הודעות, משימות ותזכורות לבד</span>${u("chev",14)}</div>
    </div>
  </div>`}},a.V.knowledge=a.V.content={title:"",render(){setTimeout(()=>a.go("home",null,!1),0)}}})(window.O);
